language: php
sudo: required

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  - DB_USERNAME=root

services:
  - mysql

before_script:
  - travis_retry composer self-update

before_install:
  - mysql -e 'create database demo;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('123456') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

install:
  - composer install
  - "php -r \"copy('.env.example', '.env');\""
  - php artisan key:generate
  - php artisan migrate:fresh --seed